spring:
  application:
    name: BookStore

  datasource:
    url: jdbc:mysql://localhost:3308/bookstore?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Ho_Chi_Minh
    username: bookstore_user
    password: bookstore_pass
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    database-platform: org.hibernate.dialect.MySQLDialect

  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml
    enabled: true

  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB

  data:
    redis:
      host: localhost
      port: 6379
      database: 0
      timeout: 2000ms
      ssl:
        enabled: false
      repositories:
        enabled: false

  mail:
    host: smtp.gmail.com
    port: 587
    username: quangnm@rabiloo.com
    password: clcjwqyozzrpamim
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

# JWT
jwt:
  signing:
    key: 0123456789abcdef0123456789abcdef0123456789abcdef0123456789abcdef

app:
  jwt:
    secret: 0123456789abcdef0123456789abcdef0123456789abcdef0123456789abcdef
    expiration-in-ms: 900000
    refresh-expiration-in-ms: 604800000

  cors:
    allowedOrigins: http://localhost:5173,http://localhost:5174

  mail:
    from: no-reply@bookstore.example.com

  otp:
    expiration-in-ms: 300000

# Cloudinary
cloudinary:
  cloud-name:
  api-key:
  api-secret:

#
r2:
  account-id: 2f4c75ecb593c2c3e06a1e1bad59cc5f
  access-key: 9589dcf926c31bd84a68bafae91d53d6
  secret-key: fb5c92c103f9184689af3f475447f9ba06cd7a546c0a27eece5f139fb9e6006a
  bucket: book-store
  endpoint: https://${r2.account-id}.r2.cloudflarestorage.com
  public-url: https://pub-8cd15cecede9479aa9a0f29042abbfae.r2.dev/

# AWS S3
aws:
  s3:
    bucketName: BookStore
    secret:
      key:
    access:
      key:

# VNPay
payment:
  vnPay:
    url:
    tmnCode:
    secretKey:
    returnUrl:
    version:
    command:
    orderType:
    max_time: 10

# GHN
GHN:
  TOKEN: 0123456789abcdef0123456789abcdef0123456789abcdef0123456789abcdef
  SHOPID: 12345

# Base URL
baseUrl: http://localhost:8081

# Chat API
chat:
  api:
    key:
    endpoint:

# Web Push Protocol
web-push:
  vapid:
    public-key: BA8CfVBkj17hVYPWHBFV71K7FkaZ7YMxW_t5E85n0tVuUSqAyvtP295c9PDDF7eiSRI4Dd7wOckew5f6Bf2zs_8
    private-key: 8IPMNuLN1-RRshnz2bzSlJE_KSvT6XKd5rj_j8mpCqo
    subject: "mailto:admin@example.com"

domain-staff-fe: http://localhost:8081/
api-url: http://localhost:8081/
