package org.example.bookstore.enums;

public enum ResponseCase {

    SUCCESS(1000, "SUCCESS"),
    OBJECT_NULL(2003, "OBJECT_NULL"),

    ERROR(4, "ERROR"),
    RECORD_ALREADY_EXIST(6, "RECORD_ALREADY_EXIST"),
    DATA_INVALID(7, "DATA_INVALID"),
    SEND_OTP_SUCCESS(8, "SEND_OTP_SUCCESS"),

    DUPLICATE(1020, "Duplicate"),
    NOT_FOUND(1404, "Cannot found!"),
    HAS_NO_DATA(1405, "Has no data"),
    NOT_LOGIN(1406, "Not login"),
    OTP_LIMITED(1407, "OTP_LIMITED"),
    CANNOT_SEND_OTP(1408, "CANNOT_SEND_OTP"),
    OTP_NOT_MATCH(1409, "OTP_NOT_MATCH"),
    PASSWORD_NOT_MATCH(1410, "PASSWORD_NOT_MATCH"),
    EXCEED_LIMIT_USER(1411, "LIMIT_USER"),
    USER_HAD_NOT_SET_PASSWORD(1412, "USER_HAD_NOT_SET_PASSWORD"),
    EXPIRED_TIME_TO_SET_PASSWORD(1413, "EXPIRED_TIME_TO_SET_PASSWORD"),
    ALREADY_SET_PASSWORD(1414, "ALREADY_SET_PASSWORD"),
    NOT_HAVE_PERMISSION(1415, "NOT_HAVE_PERMISSION"),
    YOU_NOT_EXIST_IN_THIS_COMPANY(1416, "YOU_NOT_EXIST_IN_THIS_COMPANY"),
    DUPLICATE_USER_IN_COMPANY(1417, "DUPLICATE_USER_IN_COMPANY"),
    NOT_FOUND_POST(1418, "NOT_FOUND_POST"),
    NOT_FOUND_COMPANY(1419, "NOT_FOUND_COMPANY"),
    YOUR_FRIEND_NOT_EXIST_IN_THIS_COMPANY(1420, "YOUR_FRIEND_NOT_EXIST_IN_THIS_COMPANY"),
    YOU_NOT_EXIST_IN_ANY_COMPANY(1421, "YOU_NOT_EXIST_IN_ANY_COMPANY"),
    NOT_FOUND_USER(1423, "NOT_FOUND_USER"),
    OVER_LIMIT_ROW(1424, "3000件までインポートできます。"),
    NOT_FOUND_COMMENT(1425, "NOT_FOUND_COMMENT"),
    EMAIL_SEND_FAILED(1426, "EMAIL_SEND_FAILED"),
    POST_NOT_ATTACH_ANKETTO(1427, "POST_NOT_ATTACH_ANKETTO"),
    CANNOT_VIEW_USER_VOTE_ANKETTO(1428, "CANNOT_VIEW_USER_VOTE_ANKETTO"),
    NOT_FOUND_ANKETTO(1429, "NOT_FOUND_ANKETTO"),
    UPLOAD_FILE_ERROR(1430, "UPLOAD_FILE_ERROR"),
    NOT_FOUND_NOTIFICATION(1431, "NOT_FOUND_NOTIFICATION"),
    NOT_ALLOW_CREATE_USER(1432, "NOT_ALLOW_CREATE_USER"),
    NOT_FOUND_GROUP(1433, "NOT_FOUND_GROUP"),
    USER_NOT_EXIST_IN_GROUP(1434, "USER_NOT_EXIST_IN_GROUP"),
    CANNOT_REPORT(1435, "CANNOT_REPORT"),
    TAG_USED(1436, "TAG_USED"),
    NOT_FOUND_GROUP_LINK(1437, "NOT_FOUND_GROUP_LINK"),
    NOT_FOUND_LINK(1438, "NOT_FOUND_LINK"),
    REPORT_HANDLED(1439, "REPORT_HANDLED"),
    CANNOT_MOVE_LINK_TO_GROUP_LINK_MANAGE(1440, "CANNOT_MOVE_LINK_TO_GROUP_LINK_MANAGE"),
    USER_APP_CANNOT_CREATE_LINK_IN_GROUP_LINK_MANAGE(1441, "USER_APP_CANNOT_CREATE_LINK_IN_GROUP_LINK_MANAGE"),
    OVER_LIMIT_REPORT(1442, "OVER_LIMIT_REPORT"),
    FILE_EMPTY(1443, "FILE_EMPTY"),
    INVALID_CSV_FORMAT(1444, "INVALID_CSV_FORMAT"),
    EXPIRED_TIME_TRIAL(1445, "EXPIRED_TIME_TRIAL"),
    NAME_MASTER_CONFIG_EXIST_ALREADY(1446, "NANE_MASTER_CONFIG_EXIST_ALREADY"),
    DATA_IN_USE(1447, "DATA_IN_USE"),
    EMAIL_USED(1448, "EMAIL_USED"),
    DUPLICATE_USER_IN_SYSTEM(1448, "DUPLICATE_USER_IN_SYSTEM"),
    CANNOT_DELETE(1449, "CANNOT_DELETE"),
    NOT_FOUND_DEPARTMENT(1450, "NOT_FOUND_DEPARTMENT"),
    STORY_EXPIRED(1451, "STORY_EXPIRED");

    public final int code;
    public final String message;

    ResponseCase(int code, String message){
        this.code = code;
        this.message = message;
    }
}
